local ui = require('harpoon.ui')
local mark = require('harpoon.mark')
-- local cmd_ui = require('harpoon.cmd-ui')

vim.keymap.set("n", "<leader>ha", function() mark.add_file() end)
vim.keymap.set("n", "<leader>hm", function() ui.toggle_quick_menu() end)
vim.keymap.set("n", "<leader>hp", function() ui.nav_prev() end)
vim.keymap.set("n", "<leader>hn", function() ui.nav_next() end)
vim.keymap.set("n", "<leader>hq", function() ui.nav_file(1) end)
vim.keymap.set("n", "<leader>hw", function() ui.nav_file(2) end)
vim.keymap.set("n", "<leader>he", function() ui.nav_file(3) end)
vim.keymap.set("n", "<leader>hr", function() ui.nav_file(4) end)
